config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  resources :microposts
  resources :account_activations, only: [:edit]
  resources :users
  resources :users do
    member do
      get :microposts
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]


  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="mb-6">
    <h2 class="text-red-600 font-semibold text-lg">
      <%= pluralize(object.errors.count, "error") %> prohibited this form from being saved:
    </h2>
    <ul class="list-disc list-inside text-red-500 mt-2">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% @feed_items.each do |micropost| %>
  <%= render micropost %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-sm text-gray-500 py-4 border-t">
  &copy; <%= Time.current.year %> MicropostAppTutorial
</footer>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  <%= f.file_field :image %>
  <%= f.submit "Post" %>
<% end %>

app/views/shared/_navbar.html.erb
<header class="bg-white shadow">
  <div class="container mx-auto px-4 py-4 flex justify-between items-center">
    <h1 class="text-xl font-bold">
      <%= link_to "MicropostApp", root_path, class: "text-indigo-600 hover:text-indigo-800" %>
    </h1>

    <nav class="space-x-4">
      <%= link_to "Home", root_path, class: "text-gray-700 hover:text-indigo-600" %>
      <%= link_to "Help", help_path, class: "text-gray-700 hover:text-indigo-600" %>
      <%= link_to "About", about_path, class: "text-gray-700 hover:text-indigo-600" %>
      <%= link_to "Contact", contact_path, class: "text-gray-700 hover:text-indigo-600" %>
      <% if logged_in? %>
        <%= link_to "All users", users_path, class: "text-gray-700 hover:text-indigo-600" %>
      <% end %>
      <%= link_to "Microposts", microposts_path, class: "text-gray-700 hover:text-indigo-600" %>

      <% if logged_in? %>
        <%= link_to current_user.name, current_user, class: "text-gray-700 font-semibold hover:text-indigo-600" %>
        <%= button_to "Log out", logout_path, method: :delete,
                      form_class: "inline", class: "text-red-700 hover:text-indigo-600 font-medium px-1" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "text-gray-700 hover:text-indigo-600" %>
        <%= link_to "Sign up", signup_path, class: "text-gray-700 hover:text-indigo-600" %>
      <% end %>
    </nav>
  </div>
</header>

app/views/shared/_user_list.html.erb
<% users.each do |user| %>
  <%= link_to user.name, user %>
<% end %>